name: Deploy

on:
  push:
    branches: [ production ]
    
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@v1
      with:
        args: -k -X POST https://damien-hubleur.tech:4242/deploy